# Site settings
title: FLRNT
email: allain.florent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm flrnt. I build and design web applications, mostly in Rails, sometimes
  in React, but always with love. Want to hire me ? Feel free to send me a [message][allain.florent@gmail.com].
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
